language: java

sudo: false

env:
  - OUTPUT_DIR=target ARTIFACT_NAME=hero-quest ARTIFACT_EXTENSION=.jar

cache:
  directories:
  - $HOME/.m2

install:
- mvn clean install -DskipTests -Dmaven.javadoc.skip=true -B -V

script:
- mvn test -B

before_deploy:
- tar -zcf $TRAVIS_BUILD_DIR/$OUTPUT_DIR/$TRAVIS_TAG.tar.gz -C $TRAVIS_BUILD_DIR/$OUTPUT_DIR $(find $TRAVIS_BUILD_DIR/$OUTPUT_DIR/ -maxdepth 1 -name $ARTIFACT_NAME-*$ARTIFACT_EXTENSION -printf "%f\n")

after_success:
- bash <(curl -s https://codecov.io/bash)
- mvn sonar:sonar -Dsonar.organization=$SONARQUBE_ORGANIZATION -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONARQUBE_TOKEN

deploy:
- provider: releases
  api_key: "$GITHUB_OAUTH_TOKEN"
  file: "$TRAVIS_BUILD_DIR/$OUTPUT_DIR/$TRAVIS_TAG.tar.gz"
  skip_cleanup: true
  name: $TRAVIS_TAG
  on:
    tags: true
    condition: $TRAVIS_TAG =~ ^$ARTIFACT_NAME-(([0-9]).)+([0-9]+$)

- provider: releases
  api_key: "$GITHUB_OAUTH_TOKEN"
  file: "$TRAVIS_BUILD_DIR/$OUTPUT_DIR/$TRAVIS_TAG.tar.gz"
  skip_cleanup: true
  name: $TRAVIS_TAG
  prerelease: true
  on:
    tags: true
    condition: $TRAVIS_TAG =~ ^$ARTIFACT_NAME-.*(beta|alpha|pre).*$
