#bin/bash
alias test='java -jar /opt/junit5/console/junit-platform-console-standalone-1.2.0-RC1.jar --cp /home/miguel/.m2/repository/br/com/miguelmf/hero-quest-core/1.0-SNAPSHOT/hero-quest-core-1.0-SNAPSHOT.jar:/home/miguel/.m2/repository/com/github/miguel-fontes/essentials-validation/essentials-validation-1.0/essentials-validation-essentials-validation-1.0.jar:/home/miguel/.m2/repository/org/hibernate/validator/hibernate-validator/6.0.10.Final/hibernate-validator-6.0.10.Final.jar:/home/miguel/.m2/repository/javax/validation/validation-api/2.0.1.Final/validation-api-2.0.1.Final.jar:/home/miguel/.m2/repository/org/jboss/logging/jboss-logging/3.3.2.Final/jboss-logging-3.3.2.Final.jar:/home/miguel/.m2/repository/com/fasterxml/classmate/1.3.4/classmate-1.3.4.jar:/home/miguel/.m2/repository/org/glassfish/javax.el/3.0.1-b09/javax.el-3.0.1-b09.jar:/home/miguel/.m2/repository/org/junit/jupiter/junit-jupiter-api/5.2.0/junit-jupiter-api-5.2.0.jar:/home/miguel/.m2/repository/org/apiguardian/apiguardian-api/1.0.0/apiguardian-api-1.0.0.jar:/home/miguel/.m2/repository/org/opentest4j/opentest4j/1.1.0/opentest4j-1.1.0.jar:/home/miguel/.m2/repository/org/junit/platform/junit-platform-commons/1.2.0/junit-platform-commons-1.2.0.jar:./hero-quest-cli/target/test-classes:./hero-quest-cli/target/classes:./hero-quest-core/target/test-classes:./hero-quest-core/target/classes --select-package "br.com.miguelmf"'
alias stg='git stage .'
alias st='git status'
alias cmm='git commit -m'
alias psh='git push'
alias chk='git checkout'
alias graph='git log --graph'
alias rb='git rebase'
alias b='git branch'
alias run='java -jar hero-quest-cli/target/hero-quest-cli-1.0-SNAPSHOT.jar'
alias zshupd='source ~/.zshrc'
alias zshcfg='vim ~/.zshrc'
